# Generated by Django 3.0.8 on 2020-07-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('fName', models.CharField(max_length=30)),
                ('lName', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30, null=True)),
                ('phoneNo', models.CharField(max_length=14)),
            ],
        ),
    ]
